apiVersion: v1
kind: Service
metadata:
    name: discovery-svc
    labels:
        name: discovery-svc
        app: akka-sample-cluster
spec:
    clusterIP: None
    ports:
        - name: discovery-port
          port: 2600
    selector:
        name: seed-node