apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fraud-status-server
  labels:
    name: fraud-status-server
    app: akka-sample-cluster
spec:
  replicas: 2
  template:
    metadata:
      name: fraud-status-server
      labels:
        name: status-server
    spec:
      containers:
      - name: fraud-status-server
        image: asia.gcr.io/assignment-164106/fraud-status-server:GIT_COMMIT_HASH
        ports:
        - name: cluster-port
          containerPort: 2551
        env:
          - name: SEED_DISCOVERY_SERVICE
            value: discovery-svc.default.svc.cluster.local
          - name: THIS_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CLUSTER_PORT
            value: "2551"
